### ISSUE TITLE
阿里云前端的职位有兴趣没有？

### ISSUE THREAD

**Issue by Houfeng** [huruji/blog#12]
如果有兴趣，发个简历到 zhanfeng.hzf@alibaba-inc.com

**Comment by huruji** [comment]
招应届生吗？是在杭州吗？ @Houfeng

**Comment by Houfeng** [comment]
应该还有 hc，杭州和北京都成，有兴趣的话，可以发个简历，安排个面试。

**Comment by huruji** [comment]
嗷嗷嗷，我明天发个简历过来，谢谢~~\(^o^)/~

**Comment by Houfeng** [comment]
发到上边的邮箱
